name: Build and Test

on:
  push:
   branches:
    - master

jobs:
  build-test:
    name: build-test-native
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, macos-11]
        include:
          - os: macos-11
            artifact_ext: mac
          - os: windows-latest
            artifact_ext: win

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Update Submodules (win)
        if: matrix.os == 'windows-latest' 
        run: .\updateSub.bat
        shell: pwsh

      - name: Update Submodules (mac)
        if: matrix.os == 'macos-11' 
        run: ./updateSub.sh
        shell: bash

      - name: Build (win)
        if: matrix.os == 'windows-latest' 
        run: |
          mkdir bin
          cd bin
          g++ -O3 -std=c++11 -o SameWav.exe ..\main.cpp
        shell: pwsh

      - name: Build (mac)
        if: matrix.os == 'macos-11' 
        run: |
          mkdir -p bin
          cd bin
          g++ -O3 -std=c++11 -o SameWav.app ../main.cpp
        shell: bash

      - name: Test (win)
        if: matrix.os == 'windows-latest' 
        run: |
          $temp=(.\bin\SameWav.exe tests\TestTrack.wav tests\TestTrack.wav)
          if ($temp) { exit 1 }
          .\bin\SameWav.exe tests\TestTrack.wav tests\TestTrackModified.wav | findstr "ERROR"
        shell: pwsh

      - name: Test (mac)
        if: matrix.os == 'macos-11' 
        run: |
          ./bin/SameWav.app tests/TestTrack.wav tests/TestTrack.wav | grep -q ERROR && exit 1
          ./bin/SameWav.app tests/TestTrack.wav tests/TestTrackModified.wav | grep -q ERROR || exit 1
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: SameWav-${{matrix.artifact_ext}}
          path: ./bin/

